; HEADER_BLOCK_START
; generated by ElegooSlicer 1.5.3.5 on 2026-09-21 at 22:22:51
; total layer number: 1
; filament_density: 1.25
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; filament: 1
; HEADER_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
M73 P0 R5
M106 S0
M106 P2 S0
;TYPE:Custom
;===== CC2_START_GCODE ================
;===== date: 2026-01-16-001 =====================

G90
M104 S140
M140 S60
M190 S60 A
M106 S0
BED_MESH_CALIBRATE mesh_min=86,86 mesh_max=170,170 ALGORITHM=bicubic PROBE_COUNT=5,5 ADAPTIVE=0 ADAPTIVE_MARGIN=0 FROM_SLICER=1
M204 S2000 ;Call exterior wall print acceleration
G28
M109 S210
M6211 A1 L200 T0 Q210 R210 S210
T0


G180 S7
G1 X127 Y-1.2 F20000
G1 Z0.5 F900
M73 P34 R3
M109 S210
M83
G92 E0 ;Reset Extruder
G1 E6 F251.567 
M106 S200
G1 X87 E20 F1200 
G1 F6000
M73 P36 R3
G1 X82 E0.8

M106 S0
G180 S8
G1 F20000
G92 E0 ;Reset Extruder
SET_PRINT_STATS_INFO TOTAL_LAYER=1 CURRENT_LAYER=0
;LAYER_COUNT:1
;LAYER:0
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S200


SET_PRESSURE_ADVANCE ADVANCE=0.04; Override pressure advance value
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
M73 L1
;LAYER:1
SET_PRINT_STATS_INFO TOTAL_LAYER=1 CURRENT_LAYER=1
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
G1 X167.65 Y166.15 F30000
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.5
G1 F3000
G1 X88.35 Y166.15 E2.92348
G1 X88.35 Y86.85 E2.92348
M73 P37 R3
G1 X167.65 Y86.85 E2.92348
G1 X167.65 Y166.11 E2.92201
M73 P38 R3
G1 E-.728 F1800
;WIPE_START
G1 F30000
G1 X166.45 Y166.111 E-.072
;WIPE_END
G1 X166.545 Y158.479 Z.6
G1 X167.421 Y88.003 Z.6
G1 Z.2
M73 P39 R3
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.500155
G1 F6300
G1 X166.703 Y87.284 E.03748
G1 X166.056 Y87.284 E.02385
G1 X167.216 Y88.444 E.06048
G1 X167.216 Y89.09 E.02385
G1 X165.41 Y87.284 E.0942
G1 X164.763 Y87.284 E.02385
G1 X167.216 Y89.737 E.12792
G1 X167.216 Y90.384 E.02385
G1 X164.116 Y87.284 E.16165
G1 X163.47 Y87.284 E.02385
G1 X167.216 Y91.03 E.19537
G1 X167.216 Y91.677 E.02385
G1 X162.823 Y87.284 E.2291
G1 X162.176 Y87.284 E.02385
G1 X167.216 Y92.324 E.26282
G1 X167.216 Y92.97 E.02385
G1 X161.53 Y87.284 E.29655
G1 X160.883 Y87.284 E.02385
G1 X167.216 Y93.617 E.33027
G1 X167.216 Y94.263 E.02385
G1 X160.237 Y87.284 E.364
G1 X159.59 Y87.284 E.02385
G1 X167.216 Y94.91 E.39772
G1 X167.216 Y95.557 E.02385
G1 X158.943 Y87.284 E.43144
G1 X158.297 Y87.284 E.02385
M73 P40 R3
G1 X167.216 Y96.203 E.46517
G1 X167.216 Y96.85 E.02385
G1 X157.65 Y87.284 E.49889
G1 X157.003 Y87.284 E.02385
G1 X167.216 Y97.497 E.53262
G1 X167.216 Y98.143 E.02385
G1 X156.357 Y87.284 E.56634
G1 X155.71 Y87.284 E.02385
G1 X167.216 Y98.79 E.60007
G1 X167.216 Y99.436 E.02385
G1 X155.064 Y87.284 E.63379
G1 X154.417 Y87.284 E.02385
G1 X167.216 Y100.083 E.66752
G1 X167.216 Y100.73 E.02385
M73 P40 R2
G1 X153.77 Y87.284 E.70124
G1 X153.124 Y87.284 E.02385
M73 P41 R2
G1 X167.216 Y101.376 E.73496
G1 X167.216 Y102.023 E.02385
G1 X152.477 Y87.284 E.76869
G1 X151.83 Y87.284 E.02385
G1 X167.216 Y102.67 E.80241
G1 X167.216 Y103.316 E.02385
G1 X151.184 Y87.284 E.83614
G1 X150.537 Y87.284 E.02385
G1 X167.216 Y103.963 E.86986
G1 X167.216 Y104.609 E.02385
G1 X149.891 Y87.284 E.90359
G1 X149.244 Y87.284 E.02385
G1 X167.216 Y105.256 E.93731
G1 X167.216 Y105.903 E.02385
M73 P42 R2
G1 X148.597 Y87.284 E.97104
G1 X147.951 Y87.284 E.02385
G1 X167.216 Y106.549 E1.00476
G1 X167.216 Y107.196 E.02385
G1 X147.304 Y87.284 E1.03848
G1 X146.657 Y87.284 E.02385
G1 X167.216 Y107.843 E1.07221
G1 X167.216 Y108.489 E.02385
G1 X146.011 Y87.284 E1.10593
G1 X145.364 Y87.284 E.02385
G1 X167.216 Y109.136 E1.13966
G1 X167.216 Y109.783 E.02385
G1 X144.717 Y87.284 E1.17338
M73 P43 R2
G1 X144.071 Y87.284 E.02385
G1 X167.216 Y110.429 E1.20711
G1 X167.216 Y111.076 E.02385
G1 X143.424 Y87.284 E1.24083
G1 X142.778 Y87.284 E.02385
G1 X167.216 Y111.722 E1.27456
G1 X167.216 Y112.369 E.02385
G1 X142.131 Y87.284 E1.30828
G1 X141.484 Y87.284 E.02385
G1 X167.216 Y113.016 E1.342
G1 X167.216 Y113.662 E.02385
M73 P44 R2
G1 X140.838 Y87.284 E1.37573
G1 X140.191 Y87.284 E.02385
G1 X167.216 Y114.309 E1.40945
G1 X167.216 Y114.956 E.02385
G1 X139.544 Y87.284 E1.44318
G1 X138.898 Y87.284 E.02385
G1 X167.216 Y115.602 E1.4769
G1 X167.216 Y116.249 E.02385
G1 X138.251 Y87.284 E1.51063
G1 X137.605 Y87.284 E.02385
M73 P45 R2
G1 X167.216 Y116.895 E1.54435
G1 X167.216 Y117.542 E.02385
G1 X136.958 Y87.284 E1.57808
G1 X136.311 Y87.284 E.02385
G1 X167.216 Y118.189 E1.6118
G1 X167.216 Y118.835 E.02385
G1 X135.665 Y87.284 E1.64552
G1 X135.018 Y87.284 E.02385
G1 X167.216 Y119.482 E1.67925
G1 X167.216 Y120.129 E.02385
M73 P46 R2
G1 X134.371 Y87.284 E1.71297
G1 X133.725 Y87.284 E.02385
G1 X167.216 Y120.775 E1.7467
G1 X167.216 Y121.422 E.02385
G1 X133.078 Y87.284 E1.78042
G1 X132.432 Y87.284 E.02385
G1 X167.216 Y122.068 E1.81415
G1 X167.216 Y122.715 E.02385
G1 X131.785 Y87.284 E1.84787
M73 P47 R2
G1 X131.138 Y87.284 E.02385
G1 X167.216 Y123.362 E1.8816
G1 X167.216 Y124.008 E.02385
G1 X130.492 Y87.284 E1.91532
G1 X129.845 Y87.284 E.02385
G1 X167.216 Y124.655 E1.94904
G1 X167.216 Y125.302 E.02385
G1 X129.198 Y87.284 E1.98277
G1 X128.552 Y87.284 E.02385
M73 P48 R2
G1 X167.216 Y125.948 E2.01649
G1 X167.216 Y126.595 E.02385
G1 X127.905 Y87.284 E2.05022
G1 X127.259 Y87.284 E.02385
G1 X167.216 Y127.241 E2.08394
G1 X167.216 Y127.888 E.02385
G1 X126.612 Y87.284 E2.11767
G1 X125.965 Y87.284 E.02385
M73 P49 R2
G1 X167.216 Y128.535 E2.15139
G1 X167.216 Y129.181 E.02385
G1 X125.319 Y87.284 E2.18512
G1 X124.672 Y87.284 E.02385
G1 X167.216 Y129.828 E2.21884
G1 X167.216 Y130.475 E.02385
G1 X124.025 Y87.284 E2.25256
G1 X123.379 Y87.284 E.02385
M73 P50 R2
G1 X167.216 Y131.121 E2.28629
G1 X167.216 Y131.768 E.02385
G1 X122.732 Y87.284 E2.32001
G1 X122.086 Y87.284 E.02385
G1 X167.216 Y132.414 E2.35374
G1 X167.216 Y133.061 E.02385
M73 P51 R2
G1 X121.439 Y87.284 E2.38746
G1 X120.792 Y87.284 E.02385
G1 X167.216 Y133.708 E2.42119
G1 X167.216 Y134.354 E.02385
G1 X120.146 Y87.284 E2.45491
G1 X119.499 Y87.284 E.02385
G1 X167.216 Y135.001 E2.48864
G1 X167.216 Y135.648 E.02385
M73 P52 R2
G1 X118.852 Y87.284 E2.52236
G1 X118.206 Y87.284 E.02385
G1 X167.216 Y136.294 E2.55608
G1 X167.216 Y136.941 E.02385
G1 X117.559 Y87.284 E2.58981
G1 X116.912 Y87.284 E.02385
M73 P53 R2
G1 X167.216 Y137.588 E2.62353
G1 X167.216 Y138.234 E.02385
G1 X116.266 Y87.284 E2.65726
G1 X115.619 Y87.284 E.02385
G1 X167.216 Y138.881 E2.69098
G1 X167.216 Y139.527 E.02385
G1 X114.973 Y87.284 E2.72471
G1 X114.326 Y87.284 E.02385
M73 P54 R2
G1 X167.216 Y140.174 E2.75843
G1 X167.216 Y140.821 E.02385
G1 X113.679 Y87.284 E2.79216
G1 X113.033 Y87.284 E.02385
G1 X167.216 Y141.467 E2.82588
G1 X167.216 Y142.114 E.02385
M73 P55 R2
G1 X112.386 Y87.284 E2.8596
G1 X111.739 Y87.284 E.02385
G1 X167.216 Y142.761 E2.89333
G1 X167.216 Y143.407 E.02385
G1 X111.093 Y87.284 E2.92705
G1 X110.446 Y87.284 E.02385
M73 P56 R2
G1 X167.216 Y144.054 E2.96078
G1 X167.216 Y144.7 E.02385
G1 X109.8 Y87.284 E2.9945
G1 X109.153 Y87.284 E.02385
G1 X167.216 Y145.347 E3.02823
G1 X167.216 Y145.994 E.02385
M73 P57 R2
G1 X108.506 Y87.284 E3.06195
G1 X107.86 Y87.284 E.02385
G1 X167.216 Y146.64 E3.09568
G1 X167.216 Y147.287 E.02385
G1 X107.213 Y87.284 E3.1294
G1 X106.566 Y87.284 E.02385
M73 P58 R2
G1 X167.216 Y147.934 E3.16312
G1 X167.216 Y148.58 E.02385
G1 X105.92 Y87.284 E3.19685
G1 X105.273 Y87.284 E.02385
G1 X167.216 Y149.227 E3.23057
G1 X167.216 Y149.873 E.02385
M73 P59 R2
G1 X104.627 Y87.284 E3.2643
G1 X103.98 Y87.284 E.02385
G1 X167.216 Y150.52 E3.29802
G1 X167.216 Y151.167 E.02385
G1 X103.333 Y87.284 E3.33175
G1 X102.687 Y87.284 E.02385
M73 P60 R2
G1 X167.216 Y151.813 E3.36547
G1 X167.216 Y152.46 E.02385
G1 X102.04 Y87.284 E3.3992
G1 X101.393 Y87.284 E.02385
M73 P60 R1
G1 X167.216 Y153.107 E3.43292
G1 X167.216 Y153.753 E.02385
M73 P61 R1
G1 X100.747 Y87.284 E3.46664
G1 X100.1 Y87.284 E.02385
G1 X167.216 Y154.4 E3.50037
G1 X167.216 Y155.046 E.02385
M73 P62 R1
G1 X99.454 Y87.284 E3.53409
G1 X98.807 Y87.284 E.02385
G1 X167.216 Y155.693 E3.56782
G1 X167.216 Y156.34 E.02385
G1 X98.16 Y87.284 E3.60154
G1 X97.514 Y87.284 E.02385
M73 P63 R1
G1 X167.216 Y156.986 E3.63527
G1 X167.216 Y157.633 E.02385
G1 X96.867 Y87.284 E3.66899
G1 X96.22 Y87.284 E.02385
G1 X167.216 Y158.28 E3.70271
G1 X167.216 Y158.926 E.02385
M73 P64 R1
G1 X95.574 Y87.284 E3.73644
G1 X94.927 Y87.284 E.02385
G1 X167.216 Y159.573 E3.77016
G1 X167.216 Y160.219 E.02385
M73 P65 R1
G1 X94.281 Y87.284 E3.80389
G1 X93.634 Y87.284 E.02385
G1 X167.216 Y160.866 E3.83761
G1 X167.216 Y161.513 E.02385
G1 X92.987 Y87.284 E3.87134
G1 X92.341 Y87.284 E.02385
M73 P66 R1
G1 X167.216 Y162.159 E3.90506
G1 X167.216 Y162.806 E.02385
G1 X91.694 Y87.284 E3.93879
G1 X91.047 Y87.284 E.02385
M73 P67 R1
G1 X167.216 Y163.453 E3.97251
G1 X167.216 Y164.099 E.02385
G1 X90.401 Y87.284 E4.00623
G1 X89.754 Y87.284 E.02385
G1 X167.216 Y164.746 E4.03996
G1 X167.216 Y165.393 E.02385
M73 P68 R1
G1 X89.107 Y87.284 E4.07368
G1 X88.784 Y87.284 E.01192
G1 X88.784 Y87.608 E.01193
G1 X166.892 Y165.716 E4.07368
G1 X166.246 Y165.716 E.02385
M73 P69 R1
G1 X88.784 Y88.254 E4.03995
G1 X88.784 Y88.901 E.02385
G1 X165.599 Y165.716 E4.00623
G1 X164.953 Y165.716 E.02385
M73 P70 R1
G1 X88.784 Y89.547 E3.9725
G1 X88.784 Y90.194 E.02385
G1 X164.306 Y165.716 E3.93878
G1 X163.659 Y165.716 E.02385
G1 X88.784 Y90.841 E3.90506
G1 X88.784 Y91.487 E.02385
M73 P71 R1
G1 X163.013 Y165.716 E3.87133
G1 X162.366 Y165.716 E.02385
G1 X88.784 Y92.134 E3.83761
G1 X88.784 Y92.781 E.02385
M73 P72 R1
G1 X161.719 Y165.716 E3.80388
G1 X161.073 Y165.716 E.02385
G1 X88.784 Y93.427 E3.77016
G1 X88.784 Y94.074 E.02385
G1 X160.426 Y165.716 E3.73643
G1 X159.78 Y165.716 E.02385
M73 P73 R1
G1 X88.784 Y94.721 E3.70271
G1 X88.784 Y95.367 E.02385
G1 X159.133 Y165.716 E3.66899
G1 X158.486 Y165.716 E.02385
M73 P74 R1
G1 X88.784 Y96.014 E3.63526
G1 X88.784 Y96.66 E.02385
G1 X157.84 Y165.716 E3.60154
G1 X157.193 Y165.716 E.02385
G1 X88.784 Y97.307 E3.56781
G1 X88.784 Y97.954 E.02385
M73 P75 R1
G1 X156.546 Y165.716 E3.53409
G1 X155.9 Y165.716 E.02385
G1 X88.784 Y98.6 E3.50036
G1 X88.784 Y99.247 E.02385
G1 X155.253 Y165.716 E3.46664
G1 X154.606 Y165.716 E.02385
M73 P76 R1
G1 X88.784 Y99.894 E3.43291
G1 X88.784 Y100.54 E.02385
G1 X153.96 Y165.716 E3.39919
G1 X153.313 Y165.716 E.02385
M73 P77 R1
G1 X88.784 Y101.187 E3.36547
G1 X88.784 Y101.833 E.02385
G1 X152.667 Y165.716 E3.33174
G1 X152.02 Y165.716 E.02385
G1 X88.784 Y102.48 E3.29802
G1 X88.784 Y103.127 E.02385
M73 P78 R1
G1 X151.373 Y165.716 E3.26429
G1 X150.727 Y165.716 E.02385
G1 X88.784 Y103.773 E3.23057
G1 X88.784 Y104.42 E.02385
G1 X150.08 Y165.716 E3.19684
G1 X149.433 Y165.716 E.02385
M73 P79 R1
G1 X88.784 Y105.067 E3.16312
G1 X88.784 Y105.713 E.02385
G1 X148.787 Y165.716 E3.12939
G1 X148.14 Y165.716 E.02385
G1 X88.784 Y106.36 E3.09567
G1 X88.784 Y107.006 E.02385
M73 P80 R1
G1 X147.494 Y165.716 E3.06195
G1 X146.847 Y165.716 E.02385
M73 P80 R0
G1 X88.784 Y107.653 E3.02822
G1 X88.784 Y108.3 E.02385
G1 X146.2 Y165.716 E2.9945
G1 X145.554 Y165.716 E.02385
M73 P81 R0
G1 X88.784 Y108.946 E2.96077
G1 X88.784 Y109.593 E.02385
G1 X144.907 Y165.716 E2.92705
G1 X144.26 Y165.716 E.02385
G1 X88.784 Y110.24 E2.89332
G1 X88.784 Y110.886 E.02385
M73 P82 R0
G1 X143.614 Y165.716 E2.8596
G1 X142.967 Y165.716 E.02385
G1 X88.784 Y111.533 E2.82587
G1 X88.784 Y112.179 E.02385
G1 X142.321 Y165.716 E2.79215
G1 X141.674 Y165.716 E.02385
M73 P83 R0
G1 X88.784 Y112.826 E2.75843
G1 X88.784 Y113.473 E.02385
G1 X141.027 Y165.716 E2.7247
G1 X140.381 Y165.716 E.02385
G1 X88.784 Y114.119 E2.69098
G1 X88.784 Y114.766 E.02385
G1 X139.734 Y165.716 E2.65725
G1 X139.087 Y165.716 E.02385
M73 P84 R0
G1 X88.784 Y115.413 E2.62353
G1 X88.784 Y116.059 E.02385
G1 X138.441 Y165.716 E2.5898
G1 X137.794 Y165.716 E.02385
G1 X88.784 Y116.706 E2.55608
G1 X88.784 Y117.352 E.02385
M73 P85 R0
G1 X137.148 Y165.716 E2.52235
G1 X136.501 Y165.716 E.02385
G1 X88.784 Y117.999 E2.48863
G1 X88.784 Y118.646 E.02385
G1 X135.854 Y165.716 E2.45491
G1 X135.208 Y165.716 E.02385
G1 X88.784 Y119.292 E2.42118
M73 P86 R0
G1 X88.784 Y119.939 E.02385
G1 X134.561 Y165.716 E2.38746
G1 X133.914 Y165.716 E.02385
G1 X88.784 Y120.586 E2.35373
G1 X88.784 Y121.232 E.02385
G1 X133.268 Y165.716 E2.32001
G1 X132.621 Y165.716 E.02385
M73 P87 R0
G1 X88.784 Y121.879 E2.28628
G1 X88.784 Y122.526 E.02385
G1 X131.975 Y165.716 E2.25256
G1 X131.328 Y165.716 E.02385
G1 X88.784 Y123.172 E2.21883
G1 X88.784 Y123.819 E.02385
G1 X130.681 Y165.716 E2.18511
G1 X130.035 Y165.716 E.02385
M73 P88 R0
G1 X88.784 Y124.465 E2.15139
G1 X88.784 Y125.112 E.02385
G1 X129.388 Y165.716 E2.11766
G1 X128.741 Y165.716 E.02385
G1 X88.784 Y125.759 E2.08394
G1 X88.784 Y126.405 E.02385
G1 X128.095 Y165.716 E2.05021
G1 X127.448 Y165.716 E.02385
M73 P89 R0
G1 X88.784 Y127.052 E2.01649
G1 X88.784 Y127.699 E.02385
G1 X126.801 Y165.716 E1.98276
G1 X126.155 Y165.716 E.02385
G1 X88.784 Y128.345 E1.94904
G1 X88.784 Y128.992 E.02385
G1 X125.508 Y165.716 E1.91531
G1 X124.862 Y165.716 E.02385
M73 P90 R0
G1 X88.784 Y129.638 E1.88159
G1 X88.784 Y130.285 E.02385
G1 X124.215 Y165.716 E1.84787
G1 X123.568 Y165.716 E.02385
G1 X88.784 Y130.932 E1.81414
G1 X88.784 Y131.578 E.02385
G1 X122.922 Y165.716 E1.78042
G1 X122.275 Y165.716 E.02385
M73 P91 R0
G1 X88.784 Y132.225 E1.74669
G1 X88.784 Y132.872 E.02385
G1 X121.628 Y165.716 E1.71297
G1 X120.982 Y165.716 E.02385
G1 X88.784 Y133.518 E1.67924
G1 X88.784 Y134.165 E.02385
G1 X120.335 Y165.716 E1.64552
G1 X119.689 Y165.716 E.02385
G1 X88.784 Y134.811 E1.61179
G1 X88.784 Y135.458 E.02385
M73 P92 R0
G1 X119.042 Y165.716 E1.57807
G1 X118.395 Y165.716 E.02385
G1 X88.784 Y136.105 E1.54435
G1 X88.784 Y136.751 E.02385
G1 X117.749 Y165.716 E1.51062
G1 X117.102 Y165.716 E.02385
G1 X88.784 Y137.398 E1.4769
G1 X88.784 Y138.045 E.02385
G1 X116.455 Y165.716 E1.44317
G1 X115.809 Y165.716 E.02385
M73 P93 R0
G1 X88.784 Y138.691 E1.40945
G1 X88.784 Y139.338 E.02385
G1 X115.162 Y165.716 E1.37572
G1 X114.516 Y165.716 E.02385
G1 X88.784 Y139.984 E1.342
G1 X88.784 Y140.631 E.02385
G1 X113.869 Y165.716 E1.30827
G1 X113.222 Y165.716 E.02385
G1 X88.784 Y141.278 E1.27455
G1 X88.784 Y141.924 E.02385
M73 P94 R0
G1 X112.576 Y165.716 E1.24083
G1 X111.929 Y165.716 E.02385
G1 X88.784 Y142.571 E1.2071
G1 X88.784 Y143.218 E.02385
G1 X111.282 Y165.716 E1.17338
G1 X110.636 Y165.716 E.02385
G1 X88.784 Y143.864 E1.13965
G1 X88.784 Y144.511 E.02385
G1 X109.989 Y165.716 E1.10593
G1 X109.343 Y165.716 E.02385
G1 X88.784 Y145.157 E1.0722
G1 X88.784 Y145.804 E.02385
M73 P95 R0
G1 X108.696 Y165.716 E1.03848
G1 X108.049 Y165.716 E.02385
G1 X88.784 Y146.451 E1.00475
G1 X88.784 Y147.097 E.02385
G1 X107.403 Y165.716 E.97103
G1 X106.756 Y165.716 E.02385
G1 X88.784 Y147.744 E.93731
G1 X88.784 Y148.391 E.02385
G1 X106.109 Y165.716 E.90358
G1 X105.463 Y165.716 E.02385
G1 X88.784 Y149.037 E.86986
G1 X88.784 Y149.684 E.02385
M73 P96 R0
G1 X104.816 Y165.716 E.83613
G1 X104.17 Y165.716 E.02385
G1 X88.784 Y150.331 E.80241
G1 X88.784 Y150.977 E.02385
G1 X103.523 Y165.716 E.76868
G1 X102.876 Y165.716 E.02385
G1 X88.784 Y151.624 E.73496
G1 X88.784 Y152.27 E.02385
G1 X102.23 Y165.716 E.70123
G1 X101.583 Y165.716 E.02385
G1 X88.784 Y152.917 E.66751
G1 X88.784 Y153.564 E.02385
G1 X100.936 Y165.716 E.63379
G1 X100.29 Y165.716 E.02385
G1 X88.784 Y154.21 E.60006
G1 X88.784 Y154.857 E.02385
M73 P97 R0
G1 X99.643 Y165.716 E.56634
G1 X98.996 Y165.716 E.02385
G1 X88.784 Y155.504 E.53261
G1 X88.784 Y156.15 E.02385
G1 X98.35 Y165.716 E.49889
G1 X97.703 Y165.716 E.02385
G1 X88.784 Y156.797 E.46516
G1 X88.784 Y157.443 E.02385
G1 X97.057 Y165.716 E.43144
G1 X96.41 Y165.716 E.02385
G1 X88.784 Y158.09 E.39772
G1 X88.784 Y158.737 E.02385
G1 X95.763 Y165.716 E.36399
G1 X95.117 Y165.716 E.02385
G1 X88.784 Y159.383 E.33027
G1 X88.784 Y160.03 E.02385
G1 X94.47 Y165.716 E.29654
G1 X93.823 Y165.716 E.02385
M73 P98 R0
G1 X88.784 Y160.677 E.26282
G1 X88.784 Y161.323 E.02385
G1 X93.177 Y165.716 E.22909
G1 X92.53 Y165.716 E.02385
G1 X88.784 Y161.97 E.19537
G1 X88.784 Y162.616 E.02385
G1 X91.884 Y165.716 E.16164
G1 X91.237 Y165.716 E.02385
G1 X88.784 Y163.263 E.12792
G1 X88.784 Y163.91 E.02385
G1 X90.59 Y165.716 E.0942
G1 X89.944 Y165.716 E.02385
G1 X88.784 Y164.556 E.06047
G1 X88.784 Y165.203 E.02385
G1 X89.503 Y165.921 E.03747
G1 E-.728 F1800
;WIPE_START
G1 F30000
G1 X88.784 Y165.203 E-.06097
G1 X88.784 Y165.019 E-.01103
;WIPE_END
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode 
;===== CC2_END_GCODE ================
;===== date: 2026-01-16-001 =====================


M140 S0 ;Turn-off bed
M83
G92 E0 ; zero the extruder
G1 E-1.5 F1800
G2 I0 J1 Z0.7 F3000 ; lower z a little
M106 S0
M106 P2 S0
G90
G1 Z80 F20000 ; Move print head up 
G180 S9
M104 S0
M84
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 689.93
; filament used [cm3] = 1.66
; filament used [g] = 2.07
; filament cost = 0.04
; total filament used [g] = 2.07
; total filament cost = 0.04
; total layers count = 1
; estimated printing time (normal mode) = 5m 3s
; estimated first layer printing time (normal mode) = 1m 50s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_air_filtration_during_print = 1
; activate_air_filtration_on_completion = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; additional_fan_full_speed_layer = 0
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 246x0,256x0,256x20,246x20
; bed_mesh_max = 243,245
; bed_mesh_min = 10,10
; bed_mesh_probe_distance = 22,22
; bed_temperature_formula = by_highest_temp
; bed_texture_area = 0x-10,256x-10,256x256,0x256
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0.6
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_filament_id = 0
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_line_width = 100%
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_flow_ratio = 1
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_use_efc_outline = 0
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = \n;==========CC2_CHANGE_FILAMENT_GCODE==========\n;===== date: 2026-01-16-001 =====================\nM106 S0\nM106 P2 S0\nG1 Z{min(max_layer_z+3, printable_height+0.5)} F1200\nM6211 T[next_extruder] L[flush_length] M{old_filament_e_feedrate} N{new_filament_e_feedrate} Q[old_filament_temp] R[nozzle_temperature_range_high] S[new_filament_temp]\nT[next_extruder]\n
; close_additional_fan_first_x_layers = 1
; close_fan_the_first_x_layers = 1
; combine_brims = 0
; compatible_printers_condition = 
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 90
; counterbore_hole_bridging = none
; curr_bed_type = Textured PEI Plate
; default_acceleration = 3000
; default_bed_type = 4
; default_filament_colour = ""
; default_filament_profile = "Elegoo PLA @ECC2"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Elegoo CC2 0.4 nozzle
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = ;;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; elefant_foot_layers_density = 100%
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 0
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_power_loss_recovery = printer_configuration
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enable_tower_interface_cooldown_during_tower = 0
; enable_tower_interface_features = 0
; enable_wrapping_detection = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_ams_count = 
; extruder_clearance_height_to_lid = 90
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #F2754E
; extruder_offset = 0x1.5
; extruder_printable_area = 
; extruder_printable_height = 0
; extruder_type = Direct Drive
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 80
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 50
; fan_speedup_overhangs = 1
; fan_speedup_time = 0.5
; filament_adaptive_volumetric_speed = 0
; filament_adhesiveness_category = 0
; filament_change_extrusion_role_gcode = ""
; filament_change_length = 10
; filament_colour = #F2754E
; filament_cooling_before_tower = 10
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.25
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_extruder_variant = "Direct Drive Standard"
; filament_flow_ratio = 1
; filament_flush_temp = 0
; filament_flush_volumetric_speed = 0
; filament_ids = EPLAB00
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_map = 1
; filament_map_mode = Auto For Flush
; filament_max_volumetric_speed = 21
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_printable = 3
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_self_index = 1
; filament_settings_id = "Elegoo PLA @ECC2"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >55)||(bed_temperature_initial_layer[current_extruder] >55)}M106 P3 S200\n{elsif(bed_temperature[current_extruder] >50)||(bed_temperature_initial_layer[current_extruder] >50)}M106 P3 S150\n{elsif(bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S50\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"
; filament_toolchange_delay = 0
; filament_tower_interface_pre_extrusion_dist = 10
; filament_tower_interface_pre_extrusion_length = 0
; filament_tower_interface_print_temp = -1
; filament_tower_interface_purge_volume = 20
; filament_tower_ironing_area = 4
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Elegoo
; file_start_gcode = 
; filename_format = ECC2_{nozzle_diameter[0]}_{input_filename_base}_{filament_name}_{layer_height}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 1
; first_layer_flow_ratio = 1
; first_layer_print_sequence = 0
; first_x_layer_fan_speed = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0,280,280,280,280,0,280,280,280,280,0,280,280,280,280,0
; flush_volumes_vector = 140,140,140,140,140,140,140,140
; full_fan_speed_layer = 0
; fuzzy_skin = disabled_fuzzy
; fuzzy_skin_first_layer = 0
; fuzzy_skin_layers_between_ripple_offset = 1
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_ripple_offset = 50%
; fuzzy_skin_ripples_per_layer = 15
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_flow_ratio = 1
; gap_fill_target = everywhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; grab_length = 0
; gyroid_optimized = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = elegoolink
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 0
; infill_anchor = 400%
; infill_anchor_max = 40
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = ;;
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_acceleration = 100%
; initial_layer_travel_jerk = 100%
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 3000
; inner_wall_filament_id = 0
; inner_wall_flow_ratio = 1
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; input_shaping_damp_x = 0.1
; input_shaping_damp_y = 0.1
; input_shaping_emit = 0
; input_shaping_freq_x = 0
; input_shaping_freq_y = 0
; input_shaping_type = Default
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 0.95
; internal_bridge_speed = 150%
; internal_solid_filament_id = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_flow_ratio = 1
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = 0
; ironing_angle_fixed = 0
; ironing_fan_speed = -1
; ironing_flow = 15%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 15
; ironing_type = top
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = M73 L{layer_num+1}\n;LAYER:{layer_num+1}\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER={layer_num+1}
; layer_height = 0.2
; lightning_overhang_angle = 45
; lightning_prune_angle = 45
; lightning_straightening_angle = 45
; line_width = 0.42
; long_retractions_when_cut = 0
; long_retractions_when_ec = 0
; machine_end_gcode = ;===== CC2_END_GCODE ================\n;===== date: 2026-01-16-001 =====================\n\n\nM140 S0 ;Turn-off bed\nM83\nG92 E0 ; zero the extruder\nG1 E-1.5 F1800\nG2 I0 J1 Z{max_layer_z+0.5} F3000 ; lower z a little\nM106 S0\nM106 P2 S0\nG90\n{if max_layer_z > 75}G1 Z{min(max_layer_z+5, printable_height+0.5)} F20000{else}G1 Z80 F20000 {endif}; Move print head up \nG180 S9\nM104 S0\nM84\n
; machine_load_filament_time = 51
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,500
; machine_max_jerk_e = 1,1
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_junction_deviation = 0.01
; machine_max_speed_e = 30,30
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M600
; machine_start_gcode = ;===== CC2_START_GCODE ================\n;===== date: 2026-01-16-001 =====================\n\nG90\nM104 S140\nM140 S[bed_temperature_initial_layer_single]\nM190 S[bed_temperature_initial_layer_single] A\nM106 S0\nBED_MESH_CALIBRATE mesh_min={adaptive_bed_mesh_min[0]},{adaptive_bed_mesh_min[1]} mesh_max={adaptive_bed_mesh_max[0]},{adaptive_bed_mesh_max[1]} ALGORITHM=[bed_mesh_algo] PROBE_COUNT={bed_mesh_probe_count[0]},{bed_mesh_probe_count[1]} ADAPTIVE=0 ADAPTIVE_MARGIN=0 FROM_SLICER=1\nM204 S{min(20000,max(1000,outer_wall_acceleration))} ;Call exterior wall print acceleration\nG28\nM109 S[nozzle_temperature_initial_layer]\nM6211 A1 L200 T[initial_no_support_extruder] Q[nozzle_temperature_initial_layer] R[nozzle_temperature_initial_layer] S[nozzle_temperature_initial_layer]\nT[initial_no_support_extruder]\n\n{if first_layer_print_min[1] > 0.5}\nG180 S7\nG1 X{print_bed_max[0]*0.5-1} Y-1.2 F20000\nG1 Z0.5 F900\nM109 S[nozzle_temperature_initial_layer]\nM83\nG92 E0 ;Reset Extruder\nG1 E6 F{min(1200, max(120, filament_max_volumetric_speed[initial_no_support_extruder]*60/2/2.5043))} \nM106 S200\nG1 X{print_bed_max[0]*0.5-41} E20 F{min(12000, max(1200, filament_max_volumetric_speed[initial_no_support_extruder]*60/2/2.5043))} \nG1 F6000\nG1 X{print_bed_max[0]*0.5-46} E0.8\n{else}\nG1 E30 F{min(1200, max(120, filament_max_volumetric_speed[initial_no_support_extruder]*60/2/2.5043))}\n{endif}\nM106 S0\nG180 S8\nG1 F20000\nG92 E0 ;Reset Extruder\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER=0\n;LAYER_COUNT:[total_layer_count]\n;LAYER:0
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; master_extruder_id = 1
; max_bridge_length = 10
; max_layer_height = 0.28
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 50%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_flush_dataset = 0
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 107
; nozzle_volume_type = Standard
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 2000
; outer_wall_filament_id = 0
; outer_wall_flow_ratio = 1
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 120
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_flow_ratio = 1
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parallel_printheads_bed_exclude_areas = 
; parallel_printheads_count = 1
; parking_pos_retraction = 90
; part_cooling_fan_min_pwm = 0
; physical_extruder_map = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.04
; prime_tower_brim_width = 3
; prime_tower_enable_framework = 0
; prime_tower_flat_ironing = 0
; prime_tower_infill_gap = 150%
; prime_tower_skip_points = 1
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Elegoo Centauri Carbon 2 0.4 nozzle"
; print_extruder_id = 1
; print_extruder_variant = "Direct Drive Standard"
; print_flow_ratio = 0.97
; print_order = default
; print_sequence = by layer
; print_settings_id = CC2 PLA Quality (antiwobble)
; printable_area = 0x0,256x0,256x256,0x256
; printable_height = 256
; printer_extruder_id = 1
; printer_extruder_variant = "Direct Drive Standard"
; printer_model = Elegoo Centauri Carbon 2
; printer_notes = 
; printer_settings_id = Elegoo Centauri Carbon 2 0.4 nozzle
; printer_structure = corexy
; printer_technology = FFF
; printer_variant = 0.4
; printing_by_object_gcode = 
; process_change_extrusion_role_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 0
; relative_bridge_angle = 0
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 255
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0.5
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_distances_when_ec = 10
; retraction_length = 0.8
; retraction_minimum_travel = 0.8
; retraction_speed = 30
; role_based_wipe_speed = 0
; scan_first_layer = 1
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 1
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 1
; seam_slope_min_length = 0
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; set_other_flow_ratios = 0
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 4
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament_id = 0
; sparse_infill_flow_ratio = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = cubic
; sparse_infill_rotate_template = 
; sparse_infill_speed = 200
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35
; supertack_plate_temp_initial_layer = 35
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 1
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_flow_ratio = 1
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_flow_ratio = 1
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_mms = 1
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_skip_flush = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_parallel_printheads = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = tree(auto)
; support_wan_network = 1
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 144x144/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; tool_change_on_wipe_tower = 0
; top_bottom_infill_wall_overlap = 5%
; top_shell_layers = 5
; top_shell_thickness = 0.9
; top_solid_infill_flow_ratio = 1.09
; top_surface_acceleration = 1500
; top_surface_density = 100%
; top_surface_filament_id = 0
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonic
; top_surface_speed = 200
; travel_acceleration = 0
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_angle_slow = 30
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 45
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 2
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_3mf = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; volumetric_speed_coefficients = ""
; wall_direction = ccw
; wall_distribution_count = 1
; wall_generator = classic
; wall_loops = 2
; wall_maximum_deviation = 0.025
; wall_maximum_resolution = 0.5
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1.2
; wipe_on_loops = 0
; wipe_speed = 100%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_type = type2
; wipe_tower_wall_type = rib
; wipe_tower_x = 15.000
; wipe_tower_x = 15
; wipe_tower_y = 220.000
; wipe_tower_y = 220
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; wrapping_detection_gcode = 
; wrapping_detection_layers = 20
; wrapping_exclude_area = 
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; zaa_dont_alternate_fill_direction = 0
; zaa_enabled = 0
; zaa_min_z = 0.05
; zaa_minimize_perimeter_height = 35
; first_layer_bed_temperature = 60
; bed_shape = 0x0,256x0,256x256,0x256
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


